adding AWS credentials and setup

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -39,3 +39,52 @@ jobs:
           docker logs ecommerce-app
           docker ps
           curl --fail http://localhost:3000 || exit 1
+
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: "Deploy to production"
+        run: echo "Deploying to production environment..."
+
+      - name : "Ec2 Deploy"
+        uses: easingthemes/ssh-deploy@v2.1.5
+        with:
+          ssh-private-key: ${{ secrets.EC2_SECRET }}
+          remote-user: ${{ secrets.EC2_USER }}
+          server-ip: ${{ secrets.EC2_HOST }}
+          
+      - name: "Deployment"
+        run: |
+          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
+          #!/bin/bash
+          if command -v docker &> /dev/null
+          then
+              echo "Docker is already installed."
+          else
+              echo "Docker not found. Installing Docker..."
+              sudo apt-get update && sudo apt-get install -y docker.io
+              sudo systemctl start docker
+              sudo systemctl enable docker
+              echo "Docker installed successfully."
+          fi 
+
+          if command -v nodejs &> /dev/null
+          then
+              echo "Node.js is already installed."
+          else
+              echo "Node.js not found. Installing Node.js..."
+              curl -fsSL https://deb.nodesource.com/setup_22.x | sudo bash -
+              sudo apt-get install -y nodejs
+              echo "Node.js installed successfully."
+          fi 
+          docker pull ${{ secrets.DOCKER_USER }}/ecommerce-app:latest
+          docker images
+          docker stop ecommerce-app || true
+          docker rm ecommerce-app || true
+          docker run -d -p 3000:5555 \
+          -e PORT=5555 \
+          --name ecommerce-app ${{ secrets.DOCKER_USER }}/ecommerce-app:latest
+          docker logs ecommerce-app
+          docker ps -a
+          EOF
